/* OBA AI Trader — Supabase browser auth
   Publishable key only. Never place a Supabase secret/service-role key here. */
const OBA_SUPABASE_URL = "https://dlcncozasilbfsfwcjcq.supabase.co";
const OBA_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_WzM9SwxQRaeBN3deVmx7BQ_iHw4T4n2";

const supabaseClient = window.supabase.createClient(OBA_SUPABASE_URL,OBA_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});

function obaAuthMessage(msg,ok=false){const el=document.getElementById("obaAuthMsg");if(el){el.textContent=msg;el.style.color=ok?"var(--g)":"var(--muted)"}}
function obaAuthModal(open=true){const el=document.getElementById("obaAuthModal");if(el)el.classList.toggle("open",open)}
async function obaSignIn(){const email=document.getElementById("obaAuthEmail").value.trim(),password=document.getElementById("obaAuthPassword").value;if(!email||!password)return obaAuthMessage("Enter your email and password.");obaAuthMessage("Signing in…");const {error}=await supabaseClient.auth.signInWithPassword({email,password});if(error)return obaAuthMessage(error.message);obaAuthModal(false);renderOBAAuth()}
async function obaSignUp(){const email=document.getElementById("obaAuthEmail").value.trim(),password=document.getElementById("obaAuthPassword").value;const strong=/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z\d]).{12,}$/;if(!email)return obaAuthMessage("Enter a valid email.");if(!strong.test(password))return obaAuthMessage("Use 12+ characters with uppercase, lowercase, a number and a symbol.");obaAuthMessage("Creating account…");const {data,error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+window.location.pathname}});if(error)return obaAuthMessage(error.message);obaAuthMessage(data.session?"Account created and signed in.":"Account created. Check your email to confirm your account.",true);if(data.session)obaAuthModal(false)}
async function obaSignOut(){const {error}=await supabaseClient.auth.signOut({scope:"local"});if(error)return obaAuthMessage(error.message);renderOBAAuth()}
async function getSupabaseSession(){const {data}=await supabaseClient.auth.getSession();return data.session}
function obaAuthOpen(){obaAuthModal(true);setTimeout(()=>document.getElementById("obaAuthEmail")?.focus(),50)}
function renderOBAAuth(){const safe=document.querySelector(".safe");if(!safe)return;getSupabaseSession().then(session=>{const btn=document.createElement("button");btn.id="obaAuthButton";btn.className="safe";btn.style.cssText="cursor:pointer;background:transparent;max-width:210px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap";btn.textContent=session?.user?.email||"Sign in";btn.onclick=session?obaSignOut:obaAuthOpen;safe.replaceWith(btn)})}
function injectOBAAuthUI(){if(document.getElementById("obaAuthModal"))return;const style=document.createElement("style");style.textContent=`#obaAuthModal .box{width:min(430px,100%)}#obaAuthModal .auth-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}#obaAuthModal .auth-actions .btn{flex:1;min-width:120px}#obaAuthMsg{min-height:16px;margin:8px 0 0;font-size:10px}#obaAuthHint{font-size:9px;color:var(--muted);line-height:1.5;margin-top:10px}`;document.head.appendChild(style);const wrap=document.createElement("div");wrap.id="obaAuthModal";wrap.className="modal";wrap.innerHTML=`<div class="box"><button class="x" type="button" onclick="obaAuthModal(false)">×</button><div class="ey">OBA AI TRADER</div><h3>Secure your paper account</h3><p>Sign in to connect your paper trading activity to your own account. No broker or real-money execution is enabled.</p><div class="formgrid" style="grid-template-columns:1fr"><label>Email<input id="obaAuthEmail" type="email" autocomplete="email" placeholder="you@example.com"></label><label>Password<input id="obaAuthPassword" type="password" autocomplete="current-password" placeholder="12+ chars, upper/lower, number & symbol"></label></div><div class="auth-actions"><button class="btn primary" type="button" onclick="obaSignIn()">Sign in</button><button class="btn ghost" type="button" onclick="obaSignUp()">Create account</button></div><div id="obaAuthMsg"></div><div id="obaAuthHint">Email confirmation may be required before first sign-in.</div></div>`;document.body.appendChild(wrap);wrap.addEventListener("click",e=>{if(e.target===wrap)obaAuthModal(false)})}
document.addEventListener("DOMContentLoaded",()=>{injectOBAAuthUI();renderOBAAuth();supabaseClient.auth.onAuthStateChange(()=>renderOBAAuth())});
